name: 🔄 Sync fork with upstream main

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # chaque jour à minuit UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork the main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Add upstream remote if missing
        run: |
          if ! git remote | grep -q upstream; then
            git remote add upstream https://github.com/ORIGINAL-OWNER/REPO.git
          else
            echo "🌀 Upstream already exists"
          fi

      - name: Fetch upstream/main
        run: git fetch upstream main

      - name: Merge upstream/main into main
        run: |
          git checkout main
          git merge upstream/main --no-edit || true

      - name: Push updated main to fork
        run: git push origin main
